alias ls='ls --color=auto'
alias lsa='ls --color=auto -al'
alias lsl='ls --color=auto -l'
alias cp='cp -vi'
alias mv='mv -i'
alias myip='curl www.whatismyip.com'
alias install='sudo pacman -S'
alias update='sudo pacman -Syy'
alias uninstall='sudo pacman -Rsc'
alias listorphans='sudo pacman -Qdt'
alias downloads='cd /home/quelotic/Downloads'
alias music='cd /home/quelotic/Music'
alias documents='cd /home/quelotic/Documents'
alias localhost='cd /var/www'
alias ping='ping -c 3'
alias whatismyip='echo "" && curl -s ifconfig.co | toilet -f future && echo ""'
alias mountusb='sudo mount /dev/sdb1 /mnt/usb -o rw,uid=1000,gid=1000,dmask=022,fmask=033'
alias mountpassport='sudo mount /dev/sdb1 /mnt/myPassport/ -o rw,uid=1000,gid=1000,dmask=022,fmask=033'
alias mountcamera='sudo mount /dev/mmcblk0p1 /mnt/cameraSD -o rw,uid=1000,gid=1000,dmask=022,fmask=033'
alias telegram='telegram-cli -W'
alias wifi='sudo wifi-menu'
alias cmatrix='cmatrix -a -C cyan -u 2'
upgrade(){
    sudo pacman -Syu
    echo "" > $HOME/.config/conky/pacupdates/updates.log
}
